---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	qa_router(qa_router)
	escalate(escalate)
	skill_executor(skill_executor)
	synth_answer(synth_answer)
	general_fallback(general_fallback)
	__end__([<p>__end__</p>]):::last
	__start__ --> qa_router;
	general_fallback --> synth_answer;
	skill_executor --> synth_answer;
	synth_answer --> __end__;
	qa_router -.-> escalate;
	qa_router -.-> skill_executor;
	qa_router -.-> general_fallback;
	escalate -.-> skill_executor;
	escalate -.-> synth_answer;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
